house:
  metadata:
    name: "Mijn Huis - Volledig Model"
    dimensions: { width: 4.83, depth: 11.46 }
  
  floors:
    - level: 0
      name: "Begane grond"
      height: 2.63
      rooms:
        - id: "keuken"
          polygon: [[0, 0], [2.45, 0], [2.45, 3.02], [0, 3.02]]
          label: "Keuken"
          no_walls: [[0, 3.02], [2.45, 3.02]]

        - id: "hal"
          polygon: [[2.53, 0], [3.96, 0], [3.96, 1.85], [4.83, 1.85], [4.83, 2.94], [2.53, 2.94]]
          label: "Hal"

        - id: "toilet"
          polygon: [[4.04, 0], [4.83, 0], [4.83, 1.27], [4.04, 1.27]]
          label: "Toilet"

        - id: "meterkast"
          polygon: [[4.04, 1.35], [4.83, 1.35], [4.83, 1.83], [4.04, 1.83]]
          label: "Meterkast"

        - id: "trap_bg"
          polygon: [[3.94, 2.94], [4.83, 2.94], [4.83, 6.46], [3.94, 6.46]]
          label: "Trap"

        - id: "woonkamer"
          polygon: [[0, 3.02], [3.86, 3.02], [3.86, 6.54], [4.83, 6.54], [4.83, 11.46], [0, 11.46]]
          label: "Woonkamer"
          no_walls: [[0, 3.02], [2.45, 3.02]]
    

    - level: 1
      name: "Eerste verdieping"
      height: 2.63
      rooms:
        - id: "grote_slaapkamer_voor"
          polygon: [[0, 0], [4.83, 0], [4.83, 2.94], [0, 2.94]]
          label: "Grote Slaapkamer"

        - id: "trap_v1_naar_zolder"
          polygon: [[3.94, 2.94], [4.83, 2.94], [4.83, 6.46], [3.94, 6.46]]
          label: "Trap naar Zolder"

        - id: "kantoor_achter_rechts"
          polygon: [[2.66, 6.54], [4.83, 6.54], [4.83, 9.69], [2.66, 9.69]]
          label: "Kantoor"

        - id: "slaapkamer_achter_links"
          polygon: [[0, 5.4], [2.58, 5.4], [2.58, 9.69], [0, 9.69]]
          label: "Slaapkamer Achter"

        - id: "hal"
          polygon: [[2.66, 3.02], [3.9, 3.02], [3.9, 6.46], [2.66, 6.46]]
          label: "Hal"

        - id: "badkamer"
          polygon: [[0.66, 3.02], [2.58, 3.02], [2.58, 5.32], [0.66, 5.32]]
          label: "Badkamer"

    - level: 2
      name: "Zolder"
      height: 2.40  # Zolder is vaak iets lager, pas dit aan indien nodig
      rooms:
        - id: "waskamer"
          polygon: [[0, 0], [4.83, 0], [4.83, 2.86], [0, 2.86]]
          label: "Waskamer"

        - id: "trapgat_zolder"
          polygon: [[3.94, 2.94], [4.83, 2.94], [4.83, 6.46], [3.94, 6.46]]
          label: "Trapgat"

        - id: "slaapkamer_zolder_totaal"
          polygon: [[0, 2.94], [3.86, 2.94], [3.86, 6.54], [4.83, 6.54], [4.83, 9.69], [0, 9.69]]
          label: "Zolder Slaapkamer"